@extends('layouts.master')
@section('title', 'Edit '.$course->title.' - Academy')
@section('content')
@include('academy._styles')
<div class="academy-hero"><div class="container"><a href="{{ route('academy.admin.index') }}" class="academy-hero-link"><i class="fas fa-arrow-left"></i> Academy Editor</a><h1>{{ $course->title }}</h1></div></div>
<div class="academy-body"><div class="container"><div class="row">
<div class="col-lg-5"><div class="academy-panel"><h5 class="font-weight-bold">Course settings</h5><form method="POST" enctype="multipart/form-data" action="{{ route('academy.admin.courses.update', $course) }}">@csrf
<div class="form-group"><label>Title</label><input class="form-control" name="title" value="{{ old('title', $course->title) }}" required></div><div class="form-group"><label>Description</label><textarea class="form-control" name="description" rows="4">{{ old('description', $course->description) }}</textarea></div><div class="form-group"><label>Thumbnail image</label>@if($course->thumbnail)<img src="{{ $course->thumbnail }}" alt="" class="d-block rounded mb-2" style="width:100%;height:130px;object-fit:cover"><div class="custom-control custom-checkbox mb-2"><input type="checkbox" class="custom-control-input" name="remove_thumbnail" value="1" id="removeThumbnail"><label class="custom-control-label" for="removeThumbnail">Remove current thumbnail</label></div>@endif<input class="form-control-file" type="file" name="thumbnail" accept="image/jpeg,image/png,image/webp"><small class="form-text text-muted">Uploading a new image replaces the current one.</small></div><div class="form-row"><div class="form-group col-8"><label>Icon class</label><input class="form-control" name="icon" value="{{ old('icon', $course->icon) }}"></div><div class="form-group col-4"><label>Order</label><input class="form-control" type="number" min="0" name="sort_order" value="{{ old('sort_order', $course->sort_order) }}"></div></div><div class="custom-control custom-switch mb-2"><input class="custom-control-input" type="checkbox" name="published" id="coursePublished" {{ $course->published ? 'checked' : '' }}><label class="custom-control-label" for="coursePublished">Published</label></div><div class="custom-control custom-switch mb-3"><input class="custom-control-input" type="checkbox" name="default_enrollment" id="courseDefault" {{ $course->default_enrollment ? 'checked' : '' }}><label class="custom-control-label" for="courseDefault">Available to every accepted member</label><small class="form-text text-muted">Use this for the three onboarding courses. Leave rating courses off so an administrator must assign them.</small></div><button class="btn btn-primary">Save course</button></form>
<hr><form method="POST" action="{{ route('academy.admin.courses.destroy', $course) }}" onsubmit="return confirm('Delete this course and all of its modules and self assessments?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete course</button></form></div></div>
<div class="col-lg-7"><div class="academy-panel"><h5 class="font-weight-bold">Modules</h5>@forelse($course->modules as $module)<div class="academy-list-row"><div><h6 class="mb-1">{{ $module->title }}</h6><span class="academy-status {{ $module->published ? 'text-success' : 'text-muted' }}">{{ $module->published ? 'Published' : 'Draft' }}</span><span class="academy-muted"> · order {{ $module->sort_order }}</span></div><a class="btn btn-sm btn-outline-primary" href="{{ route('academy.admin.modules.edit', $module) }}">Edit</a></div>@empty<p class="academy-muted">No modules yet.</p>@endforelse</div>
<div class="academy-panel"><h5 class="font-weight-bold">Add module</h5><form method="POST" action="{{ route('academy.admin.modules.store', $course) }}">@csrf<div class="form-group"><label>Title</label><input class="form-control" name="title" required></div><div class="form-group"><label>Description</label><textarea class="form-control" name="description" rows="2"></textarea></div><div class="form-group"><label>Google Slides Publish to Web Embed Code</label><textarea class="form-control" name="google_slides_embed_code" rows="4" placeholder="&lt;iframe src=&quot;https://docs.google.com/presentation/d/e/.../pubembed?...&quot; ...&gt;&lt;/iframe&gt;"></textarea><small class="form-text text-muted">In Google Slides, use <strong>File → Share → Publish to web → Embed</strong>, then paste the iframe code here. If set, the published Google Slides deck takes priority over locally hosted slides. Leave blank to use the local deck.</small></div><div class="form-row align-items-end"><div class="form-group col-4"><label>Order</label><input class="form-control" type="number" min="0" name="sort_order" value="0"></div><div class="form-group col-4"><div class="custom-control custom-switch mb-2"><input class="custom-control-input" type="checkbox" name="published" id="newModulePublished"><label class="custom-control-label" for="newModulePublished">Published</label></div></div><div class="form-group col-4"><button class="btn btn-primary btn-block">Add</button></div></div></form></div></div>
</div></div></div>
@stop
