@extends('layouts.master')
@section('title', 'Edit '.$module->title.' - Academy')
@section('content')
@include('academy._styles')
<div class="academy-hero"><div class="container"><a href="{{ route('academy.admin.courses.edit', $module->course) }}" class="academy-hero-link"><i class="fas fa-arrow-left"></i> {{ $module->course->title }}</a><h1>{{ $module->title }}</h1></div></div>
<div class="academy-body"><div class="container"><div class="row">
<div class="col-lg-6"><div class="academy-panel"><h5>Module settings</h5><form method="POST" action="{{ route('academy.admin.modules.update', $module) }}">@csrf
<div class="form-group"><label>Title</label><input class="form-control" name="title" value="{{ old('title',$module->title) }}" required></div><div class="form-group"><label>Description</label><textarea class="form-control" name="description">{{ old('description',$module->description) }}</textarea></div><div class="form-group"><label>Google Slides Publish to Web Embed Code</label><textarea class="form-control" name="google_slides_embed_code" rows="5" placeholder="&lt;iframe src=&quot;https://docs.google.com/presentation/d/e/.../pubembed?...&quot; ...&gt;&lt;/iframe&gt;">{{ old('google_slides_embed_code', $module->googleSlidesEditorEmbedCode()) }}</textarea><small class="form-text text-muted">Use <strong>File → Share → Publish to web → Embed</strong> in Google Slides and paste the iframe code here. <strong>Published Google Slides still takes priority.</strong> Clear this field to fall back to the locally hosted deck.</small></div><div class="form-row"><div class="form-group col-4"><label>Order</label><input class="form-control" type="number" min="0" name="sort_order" value="{{ $module->sort_order }}"></div><div class="form-group col-8 pt-4"><label><input type="checkbox" name="published" value="1" {{ $module->published?'checked':'' }}> Published</label></div></div><button class="btn btn-primary">Save module</button></form></div></div>
<div class="col-lg-6"><div class="academy-panel"><h5>Self assessment settings</h5><form method="POST" action="{{ route('academy.admin.quizzes.save',$module) }}">@csrf<div class="form-group"><label>Title</label><input class="form-control" name="title" value="{{ optional($module->quiz)->title ?? 'Self Assessment' }}" required></div><div class="form-group"><label>Passing score</label><input class="form-control" type="number" min="1" max="100" name="passing_score" value="{{ optional($module->quiz)->passing_score ?? 80 }}"></div><label><input type="checkbox" name="published" value="1" {{ optional($module->quiz)->published?'checked':'' }}> Published</label><br><button class="btn btn-primary mt-3">Save self assessment</button></form></div></div></div>
@if($module->quiz)<div class="academy-panel"><h5>Questions</h5>
@foreach($module->quiz->questions as $question)<div class="border rounded p-3 mb-3"><form method="POST" action="{{ route('academy.admin.questions.update',$question) }}">@csrf<div class="form-row"><div class="form-group col-md-9"><label>Question {{ $loop->iteration }} · {{ str_replace('_',' ',$question->type) }}</label><textarea class="form-control" name="question" required>{{ $question->question }}</textarea></div><div class="form-group col-md-3"><label>Points</label><input class="form-control" type="number" min="1" max="20" name="points" value="{{ $question->points }}" required></div></div>
@if($question->type==='written')<div class="form-group"><label>Staff rubric</label><textarea class="form-control" name="rubric" rows="5">{{ $question->rubric }}</textarea></div>@else<div class="row">@foreach($question->answers as $answer)<div class="col-md-6"><div class="form-group"><label><input type="radio" name="correct_answer" value="{{ $loop->index }}" {{ $answer->is_correct?'checked':'' }} required> {{ chr(65+$loop->index) }} correct</label><input type="hidden" name="answer_ids[]" value="{{ $answer->id }}"><input class="form-control" name="answers[]" value="{{ $answer->answer }}" required></div></div>@endforeach</div>@endif
<div class="form-group"><label>Answer explanation</label><textarea class="form-control" name="explanation">{{ $question->explanation }}</textarea></div><button class="btn btn-sm btn-primary">Save question</button></form><form class="mt-2" method="POST" action="{{ route('academy.admin.questions.destroy',$question) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></div>@endforeach
<hr><h6>Add question</h6><form method="POST" action="{{ route('academy.admin.questions.store',$module->quiz) }}">@csrf<div class="form-row"><div class="form-group col-md-8"><label>Question</label><textarea class="form-control" name="question" required></textarea></div><div class="form-group col-md-2"><label>Type</label><select class="form-control" name="type"><option value="multiple_choice">Multiple choice</option><option value="written">Written</option></select></div><div class="form-group col-md-2"><label>Points</label><input class="form-control" type="number" name="points" value="1" min="1" max="20"></div></div><div class="form-group"><label>Rubric (for written questions)</label><textarea class="form-control" name="rubric"></textarea></div><div class="row">@for($i=0;$i<4;$i++)<div class="col-md-6"><label><input type="radio" name="correct_answer" value="{{ $i }}" {{ $i===0?'checked':'' }}> {{ chr(65+$i) }} correct</label><input class="form-control mb-2" name="answers[]" placeholder="Multiple-choice answer {{ chr(65+$i) }}"></div>@endfor</div><div class="form-group mt-2"><label>Answer explanation</label><textarea class="form-control" name="explanation"></textarea></div><input type="hidden" name="sort_order" value="{{ $module->quiz->questions->count() }}"><button class="btn btn-primary">Add question</button></form></div>@else<div class="academy-panel">Save self assessment settings before adding questions.</div>@endif
</div></div>
@stop
